on:
  push:
    branches:
      - main
  workflow_dispatch:

name: ðŸš€ Deploy CRMS App

jobs:
  deploy:
    name: ðŸŽ‰ CRMS Deploy
    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš Checkout code
        uses: actions/checkout@v4

      # client
      - name: ðŸ“¦ Install client dependencies
        working-directory: client
        run: npm install --legacy-peer-deps

      - name: ðŸ›  Build React app
        working-directory: client
        run: npm run build

      - name: ðŸ“‚ Upload client to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.minventory.com.ng
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /crms.minventory.com.ng/
          local-dir: client/dist/

      # server
      - name: ðŸ“¦ Install server dependencies
        working-directory: server
        run: npm install

      # - name: ðŸ›  Build server app
      #   working-directory: server
      #   run: npm run build

      - name: ðŸ“‚ Upload server `dist/` via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.minventory.com.ng
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /crms.minventory.com.ng/backend/
          local-dir: server/

      - name: ðŸ§¼ Prepare tmp directory with fresh restart.txt
        working-directory: server
        run: |
          mkdir -p tmp
          date > tmp/restart.txt


      - name: ðŸ“‚ restart trigger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.minventory.com.ng
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /crms.minventory.com.ng/backend/tmp/
          local-dir: server/tmp/
